title: Haven Blakely-Rivers
subtitle: A Portfolio Page For My Gamedev Work (Made Using Jekyll/Devlopr)
description: >- # this means to ignore newlines until "baseurl:"
  I am a level 6 Games Design & Programming student at the University of Staffordshire and a passionate games engineer

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Portfolio
      url: /blog


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Haven Blakely-Rivers
author_bio: I am an undergraduate at University Of Staffordshire studying Games Design and Programming. I really enjoy coding and find the logic based nature of it easy to grasp and understand. I can also communicate well and work as a team because of my job as a Student Ambassador. I want to pursue a career where coding is my everyday and I work with people to make games that inspire others to make games.
author_email: "floretdev@gmail.com"
author_location: Stoke-On-Trent, UK
author_website_url: "floretdev.com"
typewrite-text: A passionate gamedev engineer who loves to code
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img
# Experiences
author_work_experiences:
            - company_name: University of Staffordshire
              company_logo: staffs.png
              company_url: https://www.staffs.ac.uk/student-life/student-ambassador-scheme
              designation: Student Ambassador
              description: Worked both solo and as a collective to foster people's interest in the university as well as helping the staff at the university.
              visibility: true

# Education
author_education_details:
              - college_logo: staffs.png
                college_name: University Of Staffordshire
                college_url: https://www.staffs.ac.uk
                college_degree: BSc Games Design and Programming (Sept. 2023 - Ongoing)
                description: Bachelor of Science Degree With a Primary Focus on Programming supplimented by games design
                visibility: true
              - college_logo: mit.png
                college_name: Access Creative College
                college_url: https://www.accesscreative.ac.uk/
                college_degree: BTEC Level 3 Games Design (Sept. 2021 - July 2023)
                description: BTEC Degree at the Norwich campus where i learnt the basics of games design and creation
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: midnighttransmission.png
                project_title: Midnight Transmission
                project_description: A top down exploration game made in Godot. I acted as a Lead Dev and World Maker
                project_url: http://floretdev.com/blog/midnight-transmission/
                visibility: true
              - project_thumbnail: goblinwithagun.png
                project_title: Goblin With a Gun
                project_description: A top down arena shooter made in unity for a uni module. Feature complete.
                project_url: http://floretdev.com/blog/goblin-with-a-gun/
                visibility: true
              - project_thumbnail: unrealstealth.png
                project_title: Unreal Stealth
                project_description: An Unreal Game made in C++ with AI and Stealth.
                project_url: http://floretdev.com/blog/unreal-stealth/
                visibility: true
              - project_thumbnail: chatterbox.png
                project_title: Chatterbox
                project_description: A Dialogue Creation & Usage System made using Unity's Experimental Node Graph System
                project_url: http://floretdev.com/blog/chatterbox/
                visibility: true

# social links
twitter_username: floretdev
github_username:  Transference-OperatorHaven
instagram_username: floretdev
# facebook_username: johndoe
linkedin_username: floretsoftware
# behance_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: floretdev@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: floretdev
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

  # jekyll admin is causing issues with github pages, so it's disabled by default
  # - jekyll-admin 

# Jekyll Admin Config
# jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  # homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
